### PR TITLE
Sam/feature/updating photon to latest

### PR DESCRIPTION
**Pull request by SamuelBellomo**
### Description
updating photon to latest

### CODE REVIEW

**Review by LukeStampfli — DISMISSED** [review]

**Review by fernando-cortez — DISMISSED** [review]

**Comment by fernando-cortez** [comment]
Just noting that I still got a `Sent 11778 bytes on NetworkDelivery: ReliableFragmentedSequenced. Event size exceeds sendQueueBatchSize: (8192).` warning log on a playthrough, but no other transport errors. We could up that value afterwards.

**Comment by SamuelBellomo** [comment]
> Just noting that I still got a `Sent 11778 bytes on NetworkDelivery: ReliableFragmentedSequenced. Event size exceeds sendQueueBatchSize: (8192).` warning log on a playthrough, but no other transport errors. We could up that value afterwards.

will fix

**Comment by SamuelBellomo** [comment]
> > Just noting that I still got a `Sent 11778 bytes on NetworkDelivery: ReliableFragmentedSequenced. Event size exceeds sendQueueBatchSize: (8192).` warning log on a playthrough, but no other transport errors. We could up that value afterwards.
> 
> will fix

@fernando-cortez fixed

**Review by fernando-cortez — APPROVED** [review]
Lgtm!

**Review by LukeStampfli — APPROVED** [review]

**Pull request merged**
