### PR TITLE
Adding ParrelSync and updating third party notice.md

### PR DESCRIPTION
**Pull request by SamuelBellomo**

### CODE REVIEW

**Comment by nomishen** [comment]
Hey @SamuelBellomo, can you please help address a few things before I send it to Sue-Lyn for review?
1. Missing [Copyright © [year] [owner] ] for UnityToonShader
2. Additional place holders at the end of the file
3. File name: Third Party Notices.md

**Comment by SamuelBellomo** [comment]
> Hey @SamuelBellomo, can you please help address a few things before I send it to Sue-Lyn for review?
> 
> 1. Missing [Copyright © [year] [owner] ] for UnityToonShader
> 2. Additional place holders at the end of the file
> 3. File name: Third Party Notices.md

1 and 2 ok
3. If you look at the files changed section of this PR, you can see the file name is Third Party Notices.md

**Comment by nomishen** [comment]
Thank you Sam. All looks good on my end and it's shared with legal to review.

**Review by fernando-cortez — APPROVED** [review]

**Comment by SamuelBellomo** [comment]
@nomishen I merged this before reading your "shared with legal for review" part. Let me know if there's any changes, I'll create a new PR

**Comment by nomishen** [comment]
It's all good. Legal came back with positive feedback.  :) Thank you for the changes.

**Pull request merged**
