### PR TITLE
In editor tutorials: Welcome dialog and table of contents [MTT-8698], [MTT-8694]

### PR DESCRIPTION
**Pull request by RikuTheFuffs**
### Description
- Added a welcome dialog to guide users on their first time experience
- Added a Table of Contents with helpful resources, that can be accessed from the `Tutorials > Show Tutorials` menu

image

image

### Issue Number(s)
- https://jira.unity3d.com/browse/MTT-8694
- https://jira.unity3d.com/browse/MTT-8698

## How to test/validate
1. Clone this branch
2. Open it with Unity
3. The welcome dialog will show up
4. Go to Tutorials > Show Tutorials to open the Table of Contents
5. Click all the links to ensure they work

### Contribution checklist
 - [x] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] JIRA ticket ID is in the PR title or at least one commit message
 - [x] Include the ticket ID number within the body message of the PR to create a hyperlink

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.coop?pullRequest=888) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.coop?pullRequest=888) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.samples.coop?pullRequest=888) it.</sub>

**Comment by gopher-atz** [comment]
small FTUE feedback:
- i would make the the welcome dialog just 2 lines bigger in y, so you can get rid of the scrollbar completely
- the tutorial window is (in my case) docked at the very right side of the editor and squashed
TutorialScreenshot, i would consider to have it floating as well initially (people can still doch later)

**Comment by gopher-atz** [comment]
when the tutorial window gets smaller in y, there's some layout issues with the menu bar on top.
it gets overlayed by the content section and you cannot click the buttons in tghe overlap zone.
TutorialScreenshot2

**Review by gopher-atz — DISMISSED** [review]

**Comment by RikuTheFuffs** [comment]
The failing tests were already failing on develop, they won't be fixed in this PR. (see https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop/pull/889 )

image

**Review by gopher-atz — APPROVED** [review]

**Pull request merged**
