### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by mohammed236**
Test

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.coop?pullRequest=853) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.samples.coop?pullRequest=853) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.samples.coop?pullRequest=853) it.</sub>

**Comment by RikuTheFuffs** [comment]
@mohammed236 can you add more context to what you're testing in this PR? If it's just a self-test one, I can close it.

**Comment by fernando-cortez** [comment]
Hi @mohammed236, without much more context on the purpose of this PR, we'll assume it was a fumble with Git, and so we'll close this PR.

**Comment by mohammed236** [comment]
I was implementing the netcode for game objects following the docs to
switch to multiplayer on my game, but when I reached the point when I have
the install the multilayer.samples.coop package, unity Field to install it
using the url package importer or the manifest file and I triple checked
that all is in the correct format,  and I had no idea where to come up with
the package, so I switched to mirror . But if you're having any idea on
where I can get the package, that will be great the guide me with the url
of it . Thanks for your help ☺️

**Pull request closed without merging**
