### PR TITLE
fix: dead imps spawning on late join

### PR DESCRIPTION
**Pull request by LPLafontaineB**
### Description (*)

This PR fixes the issue where clients connecting to an ongoing game would see imps that have already been killed and despawned by destroying the associating gameobjects on start if they are not spawned.
### Issue Number(s) (*)

Fixes issue(s): MTT-1558
### Manual testing scenarios

1. ...
2. ...
### Contribution checklist
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by pdeschain — APPROVED** [review]

**Review by LukeStampfli — APPROVED** [review]
PR looks good. This sounds like a bug to me though. Scene objects which already got despawned on the server should automatically get removed from the client.

**Review by SamuelBellomo — CHANGES_REQUESTED** [review]
This should be handled by SDK though. Is there a bug opened for this? Statically placed objects that have been despawned after joining should be despawned.

**Comment by SamuelBellomo** [comment]
> This should be handled by SDK though. Is there a bug opened for this? Statically placed objects that have been despawned after joining should be despawned.

Answering my own question
https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/1573

**Comment by SamuelBellomo** [comment]
Adding this for all PRs that have been opened since this new flow has been added. Please add your changelog here [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file

**Comment by LPLafontaineB** [comment]
yes, this is not the right fix for this bug

**Pull request closed without merging**
