### PR TITLE
feat: folder and asmdef refactoring MTT-2623

### PR DESCRIPTION
**Pull request by pdeschain**
### Description

This PR moves a bunch of files out from the Shared/Client/Server to Infrastructure, App Lifecycle and other, more appropriate (imo) locations.

I've introduced some asmdefs for things that were relatively easy to separate with messaging.

Other things like ConnectionManagement and UI still have to be part of the general "gameplay" assembly due to their tight coupling. Most of it can be resolved in separate smaller PRs targeting specific issues (we have a lot of unnecessary Bridges, that in this case turn out to be an unnecessary and needlessly complicating the code-base).

Some things have dual nature for now - Audio has a part that's completely independent of any other code, however there's a folder for audio-related scripts that are part of the clientside gameplay and ui logic. These will be separated with messaging in further PRs. 

When we separate connection management from gameplay, we would coincidentally be able to cleanly take out the UI from the domain of Client.

All of our assemblies now are named `BossRoom.***.asmdef` for easier visual navigation. All of our assemblies now use GUID-based references to make things a bit less brittle in case we decide to refactor the names of the assemblies.

There's a tall chance that some file is forgotten and that there is something that you'd want to change in this proposed folder refactor - feedback is greatly appreciated!

This is a dependency diagram as it is right now:
Screen Shot 2022-05-31 at 3 29 26 PM

### Issue Number(s)

MTT-2623
### Contribution checklist
 - [ ] Tests have been added for boss room and/or utilities pack
 - [ ] Release notes have been added to the [project changelog](../CHANGELOG.md) file and/or [package changelog](../Packages/com.unity.multiplayer.samples.coop/CHANGELOG.md) file
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] JIRA ticket ID is in the PR title or at least one commit message
 - [x] Include the ticket ID number within the body message of the PR to create a hyperlink

### CODE REVIEW

**Comment by fernando-cortez** [comment]
Should target develop, correct?

**Review by LPLafontaineB — COMMENTED** [review]
I see errors when trying to build from missing references in GameEventEditor. Also, I'm wondering why are some asmdefs using GUIDs for references while others are not? Should we be using them for all our references or keep them in plain text instead?

**Comment by pdeschain** [comment]
switched base appropriately

**Review by LPLafontaineB — DISMISSED** [review]

**Comment by SamuelBellomo** [comment]
trick for reviewers: you can use this command to get something a bit more manageable for review
git diff origin/develop...pdeschain/folder-assembly-refactor --minimal --compact-summary
(I use this with a combination of removing all entries which are just trivial folder moves to filter out the stuff I don't need to spend too much time on)
Ideally, we'd do a second PR with trivial folder moves, just make this easier to consume

**Comment by SamuelBellomo** [comment]
Adding some quick note here while waiting for this to be redone
There's no consistency on the "com" in asmdef in MTT projects, some have it, some don't, however, they all have "Unity" in them. If we could have our assemblies at least start with "unity", that'd at least be somewhat consistent with MTT names.

**Comment by SamuelBellomo** [comment]
> There's a tall chance that some file is forgotten

What do you mean exactly by this? I hope this doesn't delete any files?

**Comment by SamuelBellomo** [comment]
I still see scripts in Server and Client folders, couldn't we remove that folder hierarchy, even we don't introduce asmdefs?

**Comment by SamuelBellomo** [comment]
ScriptableObjectArchitecture
That's not very descriptive of the content. What's that folder's content really about?

**Comment by SamuelBellomo** [comment]
We need to be careful about creating a LOT of asmdefs.
Why do we need one for messages in ApplicationLifecycle?

**Comment by SamuelBellomo** [comment]
Not sure I understand what the "entity" folder is

**Comment by SamuelBellomo** [comment]
Client/Data 's content could be merged with other folders no?

**Pull request closed without merging**
