### PR TITLE
Feature/UI camera prefab

### PR DESCRIPTION
**Pull request by jilfranco-unity**
### Description (*)
Made a shared menu camera prefab for all of the menu scenes and swapped out the old cameras in the scenes for it

### Issue Number(s) (*)
[Jira ticket here](https://jira.unity3d.com/browse/MTT-2265)

### CODE REVIEW

**Review by fernando-cortez — APPROVED** [review]

**Comment by SamuelBellomo** [comment]
I'll need a bit more context on this before we add this to the release.
What is this solving?

**Comment by jilfranco-unity** [comment]
> I'll need a bit more context on this before we add this to the release. What is this solving?

These scenes are all pretty much identical, so we'd want the same camera settings carry over, and making a prefab that they all share makes it easier to keep them consistent

**Comment by SamuelBellomo** [comment]
bump, this might need to be redirected to develop

**Comment by jilfranco-unity** [comment]
This was redirected to point at develop, there were some conflicts, but they were resolved using the unity merge tool

**Review by fernando-cortez — APPROVED** [review]

**Review by SamuelBellomo — APPROVED** [review]

**Pull request merged**
