### PR TITLE
fix: error message when getting rate limited by Relay

### PR DESCRIPTION
**Pull request by LPLafontaineB**
### Description (*)

This PR adds an error message for when getting rate limited by relay during host/join process.
### Issue Number(s) (*)

Fixes issue(s): [MTT-1503](https://jira.unity3d.com/browse/MTT-1503)
### Manual testing scenarios

1. When running the game, try to get rate limited by Relay by sending too many requests when selecting the Relay connection option
2. See the error message

To make it easier to get rate-limited, you can add the line `m_UnityRelayHealthCheck = null` before line 312 in PopupPanel.cs to allow repeated calls to ListRegionAsync without having to close the window
### Contribution checklist
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with unit/integration tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by LPLafontaineB** [comment]
This looks like it is now obsolete with the integration of Lobby. Should this PR and the corresponding ticket be closed? @SamuelBellomo

**Comment by SamuelBellomo** [comment]
@LPLafontaineB  Is there zero chances relay can rate limit us? If we manually join with lobby, could there be some rate limiting issues there? cc @pdeschain

**Comment by SamuelBellomo** [comment]
@LPLafontaineB  Is there zero chances relay can rate limit us? If we manually join with lobby, could there be some rate limiting issues there? cc @pdeschain

**Comment by LPLafontaineB** [comment]
> @LPLafontaineB Is there zero chances relay can rate limit us? If we manually join with lobby, could there be some rate limiting issues there? cc @pdeschain

Well, the health check call triggering this issue is no longer done, so probably not. The only call I see is when creating a lobby, or when trying to join one. I'm not sure rate limiting can happen in those cases, but anyways the work in this specific PR is obsolete, and if this is an issue that can still occur, we would have to handle it in that other place instead

**Comment by LPLafontaineB** [comment]
Closing this as this fix is now obsolete

**Pull request closed without merging**
